"""Reusable calculation modules."""

from analysis_engine.calculations.drawdowns import (
    DrawdownResult,
    calculate_best_period_return,
    calculate_max_drawdown,
    calculate_period_return,
    calculate_worst_period_return,
)
from analysis_engine.calculations.events import EventReturnResult, calculate_event_return
from analysis_engine.calculations.fundamentals import (
    calculate_cost_ratio,
    calculate_debt_to_cash,
    calculate_gross_margin,
    calculate_market_cap_to_revenue,
    calculate_net_margin,
    calculate_operating_margin,
    calculate_revenue_growth,
    classify_growth_rate,
    classify_margin,
)
from analysis_engine.calculations.returns import (
    InvestmentComparison,
    InvestmentResult,
    calculate_annualized_return,
    calculate_final_value,
    calculate_investment_result,
    calculate_shares_bought,
    calculate_total_return,
    compare_investments,
)
from analysis_engine.calculations.valuation import (
    calculate_earnings_yield,
    calculate_eps_growth,
    calculate_forward_pe,
    calculate_margin_of_safety,
    calculate_pe_ratio,
    calculate_price_to_book,
    calculate_price_to_sales,
    classify_pe_level,
)

__all__ = [
    "DrawdownResult",
    "EventReturnResult",
    "InvestmentComparison",
    "InvestmentResult",
    "calculate_annualized_return",
    "calculate_best_period_return",
    "calculate_cost_ratio",
    "calculate_debt_to_cash",
    "calculate_earnings_yield",
    "calculate_eps_growth",
    "calculate_event_return",
    "calculate_final_value",
    "calculate_forward_pe",
    "calculate_gross_margin",
    "calculate_investment_result",
    "calculate_margin_of_safety",
    "calculate_market_cap_to_revenue",
    "calculate_max_drawdown",
    "calculate_net_margin",
    "calculate_operating_margin",
    "calculate_pe_ratio",
    "calculate_period_return",
    "calculate_price_to_book",
    "calculate_price_to_sales",
    "calculate_revenue_growth",
    "calculate_shares_bought",
    "calculate_total_return",
    "calculate_worst_period_return",
    "classify_growth_rate",
    "classify_margin",
    "classify_pe_level",
    "compare_investments",
]
